### ISSUE TITLE
Rename getquestion to question?

### ISSUE THREAD

**Issue by juliohm** [udohjeremiah/ProjectEuler.jl#3]
It is not very common in Julia to name functions with `get` prefix. I believe that `question(123)` would be more terse and easier to read, but feel free to ignore the suggestion :)

**Comment by udohjeremiah** [comment]
I had the same thought at the beginning when naming the function. I basically went through this dilemma:

- Julia functions are not named with `get` prefix, but then
- It wouldn't make sense to just call a function `question`, since no one can actually deduce from the name if it acts as a function retrieving something.

But then I said, if along the line, anyone thinks `question` is right, we'd go for `question`. So yes, we should call its `question` to follow the Julia standard.

However what do you think of functions like `submitanswer` and `checkanswer` (which might be implemented later)? We certainly can't omit the `submit` and `check` prefix from them, right?

**Comment by juliohm** [comment]
I would remove the prefix of the other functions as well. It is clear what
"submit" and "answer" means in ProjectEuler.jl

Em dom., 30 de abr. de 2023 04:16, Udoh Jeremiah ***@***.***>
escreveu:

**Comment by udohjeremiah** [comment]
Okay, thank you for your contributions. I would see into implementing them as soon as possible
